# Generated by Django 4.2.7 on 2023-11-22 11:01

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logindetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.BinaryField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=market.models.upload_path)),
            ],
        ),
    ]
