# Generated by Django 4.2.7 on 2023-11-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='role',
            field=models.CharField(default='superadmin', max_length=20),
            preserve_default=False,
        ),
    ]
