# Generated by Django 4.2.7 on 2023-12-01 18:40

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_logindetails_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=market.models.upload_path)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='logindetails',
            name='clientname',
        ),
        migrations.RemoveField(
            model_name='logindetails',
            name='date',
        ),
        migrations.RemoveField(
            model_name='logindetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='logindetails',
            name='image',
        ),
    ]
