# Generated by Django 4.2.7 on 2023-12-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_clientdetails_remove_logindetails_clientname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
