# Generated by Django 4.2.7 on 2023-12-05 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_logindetails_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campaign_name', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('sel_options', models.CharField(max_length=100)),
                ('selected_col', models.CharField(max_length=100)),
                ('client_access', models.CharField(max_length=200)),
                ('planned_impressions', models.CharField(max_length=100)),
                ('planned_cpi', models.CharField(max_length=100)),
                ('planned_clicks', models.CharField(max_length=100)),
                ('planned_cpc', models.CharField(max_length=100)),
                ('planned_session', models.CharField(max_length=100)),
                ('planned_cps', models.CharField(max_length=100)),
                ('planned_budget_impressions', models.CharField(max_length=100)),
                ('planned_budget_clicks', models.CharField(max_length=100)),
                ('planned_budget_sessions', models.CharField(max_length=100)),
                ('ctr', models.CharField(max_length=10)),
                ('deptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.clientdetails')),
            ],
        ),
    ]
