# Generated by Django 4.2.7 on 2023-12-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
