# Generated by Django 4.2.7 on 2023-12-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_clientdetails_id_alter_logindetails_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirements',
            old_name='planned_cpi',
            new_name='planned_cpm',
        ),
    ]
