# Generated by Django 4.2.7 on 2023-12-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_rename_planned_cpi_requirements_planned_cpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=100)),
                ('campaign_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('no_of_impressions', models.IntegerField()),
                ('no_of_clicks', models.IntegerField()),
                ('no_of_sessions', models.IntegerField()),
                ('cpm', models.FloatField()),
                ('cpc', models.FloatField()),
                ('cps', models.FloatField()),
                ('total_cpm', models.FloatField()),
                ('total_cpc', models.FloatField()),
                ('total_cps', models.FloatField()),
                ('ctr', models.FloatField()),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.requirements')),
            ],
        ),
    ]
